parameters:
- name: branch
  displayName: The branch to take the task code from
  default: master
- name: task
  displayName: The task to build and upload
  type: string
- name: patch
  displayName: Uploaded task patch version
  default: 10

trigger: none

pool:
  vmImage: ubuntu-20.04

resources:
  repositories:
  - repository: tasks
    type: github
    endpoint: DaniilShmelev
    name: microsoft/azure-pipelines-tasks

steps:
- checkout: self
- checkout: tasks
- task: NodeTool@0
  inputs:
    versionSpec: '15.x'
- bash: |
    sudo npm i -g tfx-cli
    tfx login --service-url https://v-dshmelev.visualstudio.com/DefaultCollection --token $(PAT)
    cd ./change-task-credentials
    npm i
    node ./index.js $(Build.SourcesDirectory)/azure-pipelines-tasks ${{ parameters.task }} ${{ parameters.patch }}
  workingDirectory: $(Build.SourcesDirectory)/task-uploader
- bash: |
    git checkout ${{ parameters.branch }}
    npm i
    mv -f ../task-uploader/index.js ./node_modules/sync-request
    node make.js build --task ${{ parameters.task }}
    tfx build tasks upload --task-path _build/Tasks/${{ parameters.task }}
  workingDirectory: $(Build.SourcesDirectory)/azure-pipelines-tasks
