pool:
  vmImage: ubuntu-20.04

resources:
  repositories:
  - repository: tasks
    type: github
    endpoint: DaniilShmelev
    name: microsoft/azure-pipelines-tasks

steps:
- checkout: self
- checkout: tasks
- task: NodeTool@0
  inputs:
    versionSpec: '15.x'
- bash: |
    sudo npm i -g tfx-cli
    tfx login --service-url https://v-dshmelev.visualstudio.com/DefaultCollection --token %PAT%
- bash: |
    npm i
    mv -f ../task-uploader/index.js ./node_modules/sync-request
    node make.js build --task JenkinsQueueJobV2
    tfx build tasks upload --task-path _build/Tasks/JenkinsQueueJobV2
  workingDirectory: $(Build.SourcesDirectory)/azure-pipelines-tasks
